define([], function() {
  return {
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "UnknownEnvironment": "The app is running in an unknown environment",
    // Calendar strings
    "CalendarSettingsTitle": "Calendar Settings",
    "CalendarSourcesLabel": "Calendar Sources",
    "AddCalendarLabel": "Add Calendar",
    "AddCalendarSharePointLabel": "SharePoint Calendar",
    "AddCalendarSharePointDescription": "Select a calendar from a SharePoint site",
    "AddCalendarExchangeLabel": "Exchange Calendar",
    "AddCalendarExchangeDescription": "Add a calendar from your mailbox or another mailbox",
    "AddCalendarIcsLabel": "Internet Calendar",
    "AddCalendarIcsDescription": "Add a calendar from an ICS URL or paste content",
    "SearchSitesLabel": "Search SharePoint Sites",
    "SelectSiteLabel": "Select Site",
    "SelectListLabel": "Select Calendar List",
    "CalendarNameLabel": "Calendar Name",
    "CalendarColorLabel": "Color",
    "FieldTitleCandidates": "Title;Subject;Event Title",
    "FieldStartCandidates": "Start Time;Start;Start Date;StartDate;StartDateTime;EventDate;Starttijd;Begindatum;Begin;Startdatum",
    "FieldEndCandidates": "End Time;End;End Date;EndDate;EndDateTime;Eindtijd;Einddatum;Einde",
    "SelectMailboxLabel": "Select Mailbox",
    "EnterMailboxLabel": "Enter another mailbox email",
    "MailboxPlaceholder": "user@example.com",
    "SelectCalendarLabel": "Select Calendar",
    "DoneLabel": "Done",
    "DeleteLabel": "Delete",
    "BackLabel": "Back",
    "SearchLabel": "Search",
    "LoadCalendarsLabel": "Load Calendars",
    "NoCalendarsFoundLabel": "No calendar lists found in this site",
    "LoadingLabel": "Loading..."
  }
});
